package lexical_elements

import (
	"bytes"
	"io"
	"os"
	"testing"
)

// captureOutput captures the stdout generated by a function f
func captureOutput(f func()) string {
	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	f()

	w.Close()
	os.Stdout = old

	var buf bytes.Buffer
	io.Copy(&buf, r)
	return buf.String()
}

func TestDisplay(t *testing.T) {
	output := captureOutput(Display)
	if output == "" {
		t.Error("Display() produced no output")
	}
	// Verify it produces a significant amount of output
	if len(output) < 100 {
		t.Errorf("Display() produced too little output: %d bytes", len(output))
	}
}
